"""Auto-generated gRPC/protobuf stubs for Techmo ASR v1p1.

This package is generated by the build system. Run:

    python hatch_build.py

or

    make proto

to regenerate from the .proto files in the proto/ directory.
"""

try:
    # Protoc places generated files in a nested path matching the proto package.
    # After generation into _proto/, the files will be at:
    #   _proto/techmo/asr/api/v1p1/asr_pb2.py
    #   _proto/techmo/asr/api/v1p1/asr_pb2_grpc.py
    from .techmo.asr.api.v1p1.asr_pb2 import (  # type: ignore
        Audio,
        AudioConfig,
        ResultConfig,
        SpeechRecognitionConfig,
        SpeechRecognitionResult,
        StreamingConfig,
        StreamingRecognizeRequest,
        StreamingRecognizeRequestConfig,
        StreamingRecognizeRequestControlMessage,
        StreamingRecognizeRequestData,
        StreamingRecognizeResponse,
        StreamingRecognizeResult,
    )
    from .techmo.asr.api.v1p1.asr_pb2_grpc import AsrStub  # type: ignore

    __all__ = [
        "Audio",
        "AudioConfig",
        "AsrStub",
        "ResultConfig",
        "SpeechRecognitionConfig",
        "SpeechRecognitionResult",
        "StreamingConfig",
        "StreamingRecognizeRequest",
        "StreamingRecognizeRequestConfig",
        "StreamingRecognizeRequestControlMessage",
        "StreamingRecognizeRequestData",
        "StreamingRecognizeResponse",
        "StreamingRecognizeResult",
    ]

except ImportError as exc:
    raise ImportError(
        "Techmo ASR gRPC stubs have not been generated yet.\n"
        "Run 'python hatch_build.py' or 'make proto' from the project root."
    ) from exc
